import { readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import path from 'node:path';
import { all, put, get, transaction, databasePath } from './db.js';
import { hashPassword } from './auth.js';

export function seed() {
 if(!all('users').some(u=>u.role==='owner')) {
  const password=process.env.ADMIN_PASSWORD||randomBytes(18).toString('base64url');
  if(password.length<8) throw new Error('ADMIN_PASSWORD must contain at least 8 characters.');
  const email=(process.env.ADMIN_EMAIL||'admin@beautyandbaby.local').trim().toLowerCase();
  put('users',{name:'Store owner',email,password:hashPassword(password),role:'owner',active:true});
  if(!process.env.ADMIN_PASSWORD) { const dest=path.join(path.dirname(databasePath),'admin-credentials.txt'); writeFileSync(dest,`Beauty & baby local admin\nEmail: ${email}\nPassword: ${password}\nSign in at /admin. Change this password in Settings > Security.\n`,{mode:0o600}); console.log(`Initial admin credentials saved to ${dest}`); }
 }
 if(get('settings','store'))return;
 transaction(()=>{
 put('settings',{id:'store',brandName:'Beauty & baby',logo:'/assets/brand.png',announcement:'Free shipping on orders over ৳2,500 · 7-day easy returns · Thoughtfully curated with care',email:'',phone:'',address:'',insideDhaka:80,outsideDhaka:150,freeShippingMin:2500,codEnabled:true,bkashEnabled:true,bkashNumber:'01700000000',nagadEnabled:true,nagadNumber:'01800000000',paymentInstructions:'Send the exact order total to our receiving number, then enter your transaction ID and sender number. Your payment will be verified by our team. Replace the seeded receiving numbers in Store design before launch.',heroEyebrow:'toys · baby care · beauty',heroTitle:'Care. Play. Glow.',heroAccent:'Everyday Magic.',heroDescription:'A joyful little world of gentle baby essentials, playful discoveries and feel-good beauty — curated for tiny moments that become big memories.',storyTitle:'Made with love,\nbacked by science.',storyDescription:'Beauty & baby brings together gentle care, playful discoveries and thoughtful gifts for your family’s everyday moments.',categoryDescription:'A little care, a little play, a little glow. Discover thoughtfully chosen essentials for every part of your family’s day.',productDescription:'Gentle essentials and delightful discoveries, chosen to make everyday care feel a little more special.',communityDescription:'Little rituals, happy discoveries and gifts from the heart. Share your everyday magic with Beauty & baby.',footerDescription:'Toys, baby care and beauty — curated into one warm, premium destination for modern families.',instagram:'',facebook:'',tiktok:'',pinterest:'',showCommunity:true,showBundles:true,primaryColor:'#4B2E83',navLinks:[{label:'Baby Care',url:'/shop?category=baby'},{label:'Toys',url:'/shop?category=toys'},{label:'Beauty',url:'/shop?category=beauty'},{label:'Gifts',url:'/shop?category=gifts'},{label:'Our Story',url:'/pages/about'}],communityItems:[{emoji:'🧸',label:'@beautyandbaby',image:''},{emoji:'🫧',label:'bath time',image:''},{emoji:'🌸',label:'gentle care',image:''},{emoji:'👶',label:'tiny moments',image:''},{emoji:'🎁',label:'gift ready',image:''}]});
 const cats=[['baby','Baby Care','Gentle daily essentials made for delicate skin.'],['toys','Toys','Play, learn and grow together.'],['beauty','Beauty','Glow naturally. Feel beautiful.'],['gifts','Gifts','Thoughtful little celebrations, wrapped with love.']];
 cats.forEach(([id,name,description],i)=>put('categories',{id,name,slug:id,description,parentId:'',image:'',style:id,order:i,active:true}));
 put('brands',{id:'beauty-baby',name:'Beauty & baby',slug:'beauty-baby',description:'Care. Play. Glow.',image:'/assets/brand.png',active:true});
 const samples=JSON.parse(readFileSync(new URL('./prototype-products.json',import.meta.url),'utf8'));
 samples.push({id:9,name:'Cuddle Soft Toy',price:850,tag:'New',type:'toy',desc:'A sweet, soft companion for little moments of play.'},{id:10,name:'Signature Gift Wrap',price:1100,tag:'',type:'gift',desc:'A beautifully finished gift box, ready for someone special.'},{id:11,name:'Everyday Beauty Care',price:1450,tag:'New',type:'oil',desc:'A simple addition to your daily self-care ritual.'});
 samples.forEach(p=>put('products',{id:String(p.id),name:p.name,slug:p.name.toLowerCase().replaceAll(/[^a-z0-9]+/g,'-'),sku:'BB-'+String(p.id).padStart(4,'0'),description:p.desc,ingredients:'',usage:'',price:p.price,comparePrice:p.tag==='Sale'?p.price+250:0,stock:30,lowStock:5,categoryId:p.id===9?'toys':p.id===10||p.id===7?'gifts':p.id===11?'beauty':'baby',subcategoryId:'',brandId:'beauty-baby',tag:p.tag,type:p.type,images:[],active:true,featured:p.id<=4,giftEligible:[1,3,4,9,10,11].includes(p.id),variants:[],seoTitle:'',seoDescription:''}));
 const pages={about:['Our story','Beauty & baby is a warm little world of baby care, toys, beauty and thoughtful gifts. We believe everyday family moments deserve a little magic.'],delivery:['Delivery information','We deliver across Bangladesh. Delivery inside Dhaka is ৳80 and outside Dhaka is ৳150. Orders of ৳2,500 or more qualify for free shipping. Our team will contact you to confirm your order and delivery timing.'],returns:['Returns & exchanges','Contact our team within 7 days of delivery to request a return. Items should be unused, unopened and in their original packaging. For hygiene reasons, opened personal care products cannot be returned unless they arrived damaged or incorrect. Keep your order number ready when contacting us.'],contact:['Get in touch','Have a question about your order or need help choosing a product? Use the contact details below, or track your order online.'],faq:['Frequently asked questions','How do I order?\nAdd your favorites to your bag and continue to checkout. You can order as a guest or create an account.\n\nHow do I pay?\nCash on delivery is available. bKash and Nagad appear at checkout when configured by the store.\n\nHow do I track my order?\nUse your order reference and the mobile number entered at checkout on our Track order page.'],privacy:['Privacy policy','We collect the contact and delivery details needed to process your order. Registered customers can view their orders in their account. Contact the store to request a copy or deletion of your personal data.'],terms:['Terms of service','Prices are in Bangladeshi taka. Orders are subject to stock availability and confirmation. Manual mobile payments are verified before processing. Contact us for assistance with an order.']};
 Object.entries(pages).forEach(([slug,[title,content]])=>put('pages',{id:slug,slug,title,content,active:true}));
 });
}
